### PR TITLE
[Mac] feat: Support screen capture for macOS.

### PR DESCRIPTION
**Pull request by cloudwebrtc**
Try adding screen sharing for macOS:
TODO: (1/5)
- [x] Screen capture
- [x] select screen
- [x] Window capture
- [x] Select window
- [x] Get thumbnail for preview

### CODE REVIEW

**Comment by cloudwebrtc** [comment]
The windows can now be enumerated.
image

But have some issues here, when I drag the captured window and change the size, the image will crack. There may be a bug in libwebrtc. @hiroshihorie @davidliu @davidzhao  Have any ideas? xD
image
image

This problem has been bothering me for two days.

**Review by hiroshihorie — APPROVED** [review]
Wow great work. I'll think about the resize issue.

**Comment by cloudwebrtc** [comment]
Here is some code showing how to call it, maybe it can help you to test on swift sdk
https://github.com/flutter-webrtc/flutter-webrtc/pull/940/files#diff-dff3e74bce71fb4d131c17ba1af18ac75e9b370124e392da2518866db2a9386c

**Comment by davidliu** [comment]
Haven't digged into the code, but just from the looks of the image, it seems like the frame isn't updated with the correct dimensions. Since the video frame is a continguous array, if the width isn't updated, the pixels would spill into the next/previous row. That explains why there's a slant and the image is seemingly wrapping around. (I assume the slant gets worse as you expand/contract the window.)

**Comment by davidzhao** [comment]
@hiroshihorie your MacOS version didn't have this issue IIRC. Perhaps there are some insights there?

**Comment by cloudwebrtc** [comment]
okay,  everything is working fine now, a story about the width not being divisible by 32.
image

**Comment by hiroshihorie** [comment]
wow nice find, needs to multiple of 32 ?

**Comment by cloudwebrtc** [comment]
Yes, When the width can be divisible by 32, the picture is fine. Other widths must be added with some numbers, which can be divisible by 32, But at this time, you need to remove the extra width, a black edge xD, It may be related to the capture mechanism of CGWindowListCreateImage. For now, it works perfectly. I still need to do some testing in intel mac, to make sure it works 100%.

https://github.com/webrtc-sdk/webrtc/pull/24/files#diff-0cd0a6ae24c482adb040d158c9b2e162f20c03741100c9036083360d7d1be694R81

**Review by davidzhao — APPROVED** [review]
great work tracking this one down!

**Comment by cloudwebrtc** [comment]
hey @vickyleu, Thanks for reporting the issue, and are there any steps to reproduce？
BTW, macOS version and cpu (m1 or intel) is useful info.

**Pull request merged**
