### PR TITLE
Update to m125.

### PR DESCRIPTION
**Pull request by cloudwebrtc**
Use M125 as the latest version and migrate historical patches to m125

Patches Group:

## 1. Update README.md https://github.com/webrtc-sdk/webrtc/pull/119/commits/b6c65fc7f0e81ed305e5578467b7198833665352
* Add Apache-2.0 license and some note to README.md. (#9)
* Updated readme detailing changes from original (#42)
* Adding membrane framework (#51)
* Updated readme (#83)

## 2. Audio Device Optimization https://github.com/webrtc-sdk/webrtc/pull/119/commits/7454824ea6481cae2f70ad58fb1e1eb5d3ecdc88
* allow listen-only mode in AudioUnit, adjust when category changes (https://github.com/webrtc-sdk/webrtc/pull/2)
* release mic when category changes (https://github.com/webrtc-sdk/webrtc/pull/5)
* Change defaults to iOS defaults (https://github.com/webrtc-sdk/webrtc/pull/7)
* Sync audio session config (https://github.com/webrtc-sdk/webrtc/pull/8)
* feat: support bypass voice processing for iOS. (https://github.com/webrtc-sdk/webrtc/pull/15)
* Remove MacBookPro audio pan right code (https://github.com/webrtc-sdk/webrtc/pull/22)
* fix: Fix can't open mic alone when built-in AEC is enabled. (https://github.com/webrtc-sdk/webrtc/pull/29)
* feat: add audio device changes detect for windows. (https://github.com/webrtc-sdk/webrtc/pull/41)
* fix Linux compile (https://github.com/webrtc-sdk/webrtc/pull/47)
* AudioUnit: Don't rely on category switch for mic indicator to turn off (https://github.com/webrtc-sdk/webrtc/pull/52)
* Stop recording on mute (turn off mic indicator) (https://github.com/webrtc-sdk/webrtc/pull/55)
* Cherry pick audio selection from m97 release (https://github.com/webrtc-sdk/webrtc/pull/35)
* [Mac] Allow audio device selection (https://github.com/webrtc-sdk/webrtc/pull/21)
* RTCAudioDeviceModule.outputDevice / inputDevice getter and setter (https://github.com/webrtc-sdk/webrtc/pull/80)
* Allow custom audio processing by exposing AudioProcessingModule (https://github.com/webrtc-sdk/webrtc/pull/85)
* Expose audio sample buffers for Android (https://github.com/webrtc-sdk/webrtc/pull/89)
* feat: add external audio processor for android. (https://github.com/webrtc-sdk/webrtc/pull/103)
* android: make audio output attributes modifiable (https://github.com/webrtc-sdk/webrtc/pull/118)
* Fix external audio processor sample rate calculation (https://github.com/webrtc-sdk/webrtc/pull/108)
* Expose remote audio sample buffers on RTCAudioTrack (https://github.com/webrtc-sdk/webrtc/pull/84)
* Fix memory leak when creating audio CMSampleBuffer https://github.com/webrtc-sdk/webrtc/pull/86

## 3. Simulcast/SVC support for iOS/Android.  https://github.com/webrtc-sdk/webrtc/pull/119/commits/b0b9fe93b1b4f0f8cdd80919a05f999124ff8bce
    
- Simulcast support for iOS SDK (#4)
- Support for simulcast in Android SDK (#3)
- include simulcast headers for mac also (#10)
- Fix simulcast using hardware encoder on Android (#48)
- Add scalabilityMode support for AV1/VP9. (#90)

## 4. Android improvements. https://github.com/webrtc-sdk/webrtc/pull/119/commits/9aaaab5a20fec2c84616ca709ac9c1aae6de9225
- Start/Stop receiving stream method for VideoTrack (#25)
- Properly remove observer upon deconstruction (#26)
- feat: Expose setCodecPreferences/getCapabilities for android. (#61)
- fix: add WrappedVideoDecoderFactory.java. (#74)

## 5. Darwin improvements https://github.com/webrtc-sdk/webrtc/pull/119/commits/a13ea178e46ee2ab222f1553c9164b6556e1abd8
- [Mac/iOS] feat: Add RTCYUVHelper for darwin. (#28)
- Cross-platform `RTCMTLVideoView` for both iOS / macOS (#40)
- rotationOverride should not be assign (#44)
- [ObjC] Expose properties / methods required for AV1 codec support (#60)
- Workaround: Render PixelBuffer in RTCMTLVideoView (#58)
- Improve iOS/macOS H264 encoder (#70)
- fix: fix video encoder not resuming correctly upon foregrounding (#75).
- add PrivacyInfo.xcprivacy to darwin frameworks. (#112)
- Add NSPrivacyCollectedDataTypes key to xcprivacy file (#114)
- Thread-safe `RTCInitFieldTrialDictionary` (#116)
- Set RTCCameraVideoCapturer initial zoom factor (#121)
- Unlock configuration before starting capture session (#122)

## 6. Desktop Capture for macOS. https://github.com/webrtc-sdk/webrtc/pull/119/commits/841d78f0631aff91590c1493909c4f3fccd8fafe
- [Mac] feat: Support screen capture for macOS. (#24) (#36)
- fix: Get thumbnails asynchronously. (#37)
- fix: Use CVPixelBuffer to build DesktopCapture Frame, fix the crash caused by non-CVPixelBuffer frame in RTCVideoEncoderH264 that cannot be cropped. (#63)
- Fix the crash when setting the fps of the virtual camera. (#62)

## 7. Frame Cryptor Support. https://github.com/webrtc-sdk/webrtc/pull/119/commits/fc08745d9c5218aed45829942a3590c97c19c76a
- feat: Frame Cryptor (aes gcm/cbc). (#54)
- feat: key ratchet/derive. (#66)
- fix: skip invalid key when decryption failed. (#81)
- Improve e2ee, add setSharedKey to KeyProvider. (#88)
- add failure tolerance for framecryptor. (#91)
- fix h264 freeze. (#93)
- Fix/send frame cryptor events from signaling thread (#95)
- more improvements for E2EE. (#96)
- remove too verbose logs (#107)
- Add key ring size to keyProviderOptions. (#109)

## 8. Other improvements. https://github.com/webrtc-sdk/webrtc/pull/119/commits/eed6c8a1bff6c0e16a850be07597e59ed8a68d7e
- Added yuv_helper (#57)
- ABGRToI420, ARGBToI420 & ARGBToRGB24 (#65)
- more yuv wrappers (#87)
- Fix naming for yuv helper (#113)
- Fix missing `RTC_OBJC_TYPE` macros (#100)

### CODE REVIEW

**Comment by cloudwebrtc** [comment]
All PRs have been merged into this PR (from m114_release and new PRs added later), and compiled on all platforms.

**Comment by davidliu** [comment]
Nice! Were there any merge conflicts or did the patches port cleanly?

**Comment by cloudwebrtc** [comment]
Some code line position conflicts can be fixed with simple modifications.
And some factory function changes such as `RTCVideoEncoderSimulcastBuilder`.
As well as conflicts between existing WebRTC patches and the patches we committed, such as `setCodecPreferences/getCapabilities`, I removed the livekit implementation.
https://github.com/webrtc-sdk/webrtc/pull/61

I'll do a full round of testing tomorrow to make sure most of the features involved work.

**Review by davidliu — APPROVED** [review]
LGTM!

**Pull request merged**
