### PR TITLE
Apply patches to m97

### PR DESCRIPTION
**Pull request by davidliu**
Note: PRs #11 and #12 were dropped as they were patches originally taken from the upstream, and are no longer needed.

### CODE REVIEW

**Review by davidzhao — APPROVED** [review]
Looks good! I've enabled individual commit merging for the repo. that might be a better way to move forward to keep them separate. wdyt?

**Comment by davidliu** [comment]
What's individual commit merging, and how does that differ?

**Comment by davidzhao** [comment]
it will keep all the commits in main individually, rather than all together. It might make it easier to cherry pick changes to future branches

**Comment by davidliu** [comment]
Ah, instead of squashing, got it.

**Comment by hiroshihorie** [comment]
Nice !! No more simulcast factory null checks for android 🙂

**Comment by davidliu** [comment]
The null checks were originally from upstream so they're taken care of now.

**Pull request merged**
