### PR TITLE
update to m114

### PR DESCRIPTION
**Pull request by cloudwebrtc**
Patches Group:

## 1, Readme and License https://github.com/webrtc-sdk/webrtc/pull/76/commits/aaf97b76f29ad037fd34303b20ff1bd5d41c3a28

- Add Apache-2.0 license and some notes to README.md (#9).
-  Updated readme detailing changes from original (#42)
-  Adding membrane framework (#51)

## 2, Audio Device Optimization https://github.com/webrtc-sdk/webrtc/pull/76/commits/56b71198263105f16c00045cce3c491b84f64ea9

- allow listen-only mode in AudioUnit, adjust when category changes (#2)
- release mic when category changes (#5)
- Change defaults to iOS defaults (#7)
- Sync audio session config (#8)
- feat: support bypass voice processing for iOS. (#15)
- Remove MacBookPro audio pan right code (#22)
 - fix: Fix can't open mic alone when built-in AEC is enabled. (#29)
- feat: add audio device changes detect for Windows. (#41)
- fix Linux compile (#47)
- AudioUnit: Don't rely on category switch for mic indicator to turn off (#52)
- Stop recording on mute (turn off mic indicator) (#55)
- Cherry pick audio selection from m97 release (#35)
-  [Mac] Allow audio device selection (#21)
-  Simplify output / input audio device setting and getting through properties (#80)

## 3, Simulcast support for iOS/Android. https://github.com/webrtc-sdk/webrtc/pull/76/commits/03dc44e67a05bf89820a0be842d3e46c0027cace
    
- Simulcast support for iOS SDK (#4)
- Support for simulcast in Android SDK (#3)
- include simulcast headers for mac also (#10)
- Fix simulcast using hardware encoder on Android (#48)

## 4, Android improvements https://github.com/webrtc-sdk/webrtc/pull/76/commits/378dc0be93020dc54a0df8567be74fd09a4bf140

- Start/Stop receiving stream method for VideoTrack (#25)
- Properly remove observer upon deconstruction (#26)
- feat: Expose setCodecPreferences/getCapabilities for android. (#61)
- fix: add WrappedVideoDecoderFactory.java. (#74)

## 5, Darwin improvements https://github.com/webrtc-sdk/webrtc/pull/76/commits/2abe97d9a99c87d987d6b3a3a24888950e4265bc

- [Mac/iOS] feat: Add RTCYUVHelper for darwin. (#28)
- Cross-platform `RTCMTLVideoView` for both iOS / macOS (#40)
- rotationOverride should not be assign (#44)
- [ObjC] Expose properties / methods required for AV1 codec support (#60)
- Workaround: Render PixelBuffer in RTCMTLVideoView (#58)
- Improve iOS/macOS H264 encoder (#70)
- Fix the video encoder not resuming correctly upon foregrounding (#75)
- 
## 6,   Desktop Capture for macOS. https://github.com/webrtc-sdk/webrtc/pull/76/commits/bd6ba72838f85e52aa3e53dc333b9c0caa2ddbc9

- [Mac] feat: Support screen capture for macOS. (#24)
- fix: Get thumbnails asynchronously. (#37)
- fix: Use CVPixelBuffer to build DesktopCapture Frame, fix the crash caused by non-CVPixelBuffer frame in (#63)
- Fix the crash when setting the fps of the virtual camera. (#62)

## 7,  Frame Cryptor Support. https://github.com/webrtc-sdk/webrtc/pull/76/commits/4dd33c610fb0e9eee69fcba3616ca106fb5b6875

- feat: Frame Cryptor (aes gcm/cbc). (#54)
- feat: key ratchet/derive. (#66)
- fix: skip invalid key when decryption failed. (#81)

## 8,     Other improvements. https://github.com/webrtc-sdk/webrtc/pull/76/commits/e86aeeed74bb438f10aba2e050e7f3ed4a67ab65
- Added yuv_helper (#57)
- ABGRToI420, ARGBToI420 & ARGBToRGB24 (#65)

### CODE REVIEW

**Comment by cloudwebrtc** [comment]
hey @hiroshihorie, when you have time, can you help to see this diff https://github.com/webrtc-sdk/webrtc/commit/56b71198263105f16c00045cce3c491b84f64ea9? I spent a lot of time re-adapting this big patch (which works fine), maybe you can take a look and prevent me from triggering new bugs.

**Comment by hiroshihorie** [comment]
@cloudwebrtc  Sure, does it work fine ? Would like to compile it and test it out or can you send me a framework ?

**Comment by cloudwebrtc** [comment]
@hiroshihorie sure, here is the framework
https://github.com/webrtc-sdk/Specs/releases/tag/114.5735.01

Yes, it can run correctly on flutter iOS/macOS, and I also fixed the bug that the iOS enters the background and stops sending video track, maybe you can check that it works correctly in Swift

**Comment by davidzhao** [comment]
yay 🎆

**Comment by hiroshihorie** [comment]
Great job !

**Pull request merged**
